name: trader-moni
version: "3.9"
services:
  gateway-service:
    build: ./services/gateway-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - USER_SERVICE_URL=http://user-service:3001
      - ORDER_SERVICE_URL=http://order-service:8081
      - PAYMENT_SERVICE_URL=http://payment-service:8082
      - NOTIFICATION_SERVICE_URL=http://notification-service:3002
      - SERVICE_VERSION=1.0.0
    depends_on:
      - user-service
      - order-service
      - payment-service
      - notification-service
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SERVICE_NAME=user-service
      - SERVICE_VERSION=1.0.0
      - NODE_ENV=development
      - DATABASE_URL=memory://localhost
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  order-service:
    build: ./services/order-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - SERVICE_VERSION=1.0.0
      - PAYMENT_SERVICE_URL=http://payment-service:8082
      - DATABASE_URL=memory://localhost
    depends_on:
      - payment-service
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8081/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  payment-service:
    build: ./services/payment-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - SERVICE_NAME=payment-service
      - SERVICE_VERSION=1.0.0
      - LOG_LEVEL=INFO
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8082/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-service:
    build: ./services/notification-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SERVICE_NAME=notification-service
      - SERVICE_VERSION=1.0.0
      - NODE_ENV=development
      - EMAIL_PROVIDER=mock
      - SMS_PROVIDER=mock
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3002/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  trader-moni-network:
    name: trader-moni-network
    driver: bridge
