apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: trader-moni
  labels:
    app: notification-service
    tier: backend
data:
  PORT: "3002"
  SERVICE_NAME: "notification-service"
  SERVICE_VERSION: "1.0.0"
  NODE_ENV: "production"
  EMAIL_PROVIDER: "mock"
  SMS_PROVIDER: "mock"
  LOG_LEVEL: "INFO"