apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: trader-moni
  labels:
    app: order-service
    tier: backend
data:
  PORT: "8081"
  SERVICE_NAME: "order-service"
  SERVICE_VERSION: "1.0.0"
  PAYMENT_SERVICE_URL: "http://payment-service:8082"
  DATABASE_URL: "memory://localhost"
  LOG_LEVEL: "INFO"