apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: trader-moni
  labels:
    app: payment-service
    tier: backend
data:
  PORT: "8082"
  SERVICE_NAME: "payment-service"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  SPRING_PROFILES_ACTIVE: "kubernetes"