apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: trader-moni
  labels:
    app: gateway-service
    tier: backend
data:
  PORT: "3001"
  SERVICE_NAME: "user-service"
  SERVICE_VERSION: "1.0.0"
  NODE_ENV: "development"
  DATABASE_URL: "memory://localhost"
  LOG_LEVEL: "INFO"

