server:
  port: ${PORT:8082}

service:
  name: ${SERVICE_NAME:payment-service}
  version: ${SERVICE_VERSION:1.0.0}
  environment: ${ENVIRONMENT:development}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.payment: ${LOG_LEVEL:INFO}