apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: trader-moni
  labels:
    app: notification-service
    tier: backend
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: notification-service
      tier: backend
  template:
    metadata:
      labels:
        app: notification-service
        tier: backend
        version: v1
    spec:
      containers:
      - name: notification-service
        image: trader-moni/notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: notification-config
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}