apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: trader-moni
  labels:
    app: payment-service
    tier: backend
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: payment-service
      tier: backend
  template:
    metadata:
      labels:
        app: payment-service
        tier: backend
        version: v1
    spec:
      containers:
      - name: payment-service
        image: trader-moni/payment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: payment-config
        env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: ENCRYPTION_KEY
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "300m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}