apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: trader-moni
  labels:
    app: gateway-service
    tier: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gateway-service
    tier: gateway