apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
    tier: backend
  name: notification-service
  namespace: trader-moni
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: notification-service
    tier: backend
  type: ClusterIP

