apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: trader-moni
  labels:
    app: order-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: order-service
    tier: backend