apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: trader-moni
  labels:
    app: payment-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: payment-service
    tier: backend